import { Producto, Categoria, MovimientoStock, Perfil } from '../types/database';

export const mockCategorias: Categoria[] = [
  { id: 'cat-1', nombre: 'Componentes Electrónicos', descripcion: 'Sensores, microcontroladores y placas', creado_en: new Date().toISOString() },
  { id: 'cat-2', nombre: 'Herramientas Industriales', descripcion: 'Herramientas de mano y calibradores', creado_en: new Date().toISOString() },
  { id: 'cat-3', nombre: 'Material de Embalaje', descripcion: 'Cajas de cartón corrugado y palets', creado_en: new Date().toISOString() },
  { id: 'cat-4', nombre: 'Seguridad y EPP', descripcion: 'Guantes, cascos y protección', creado_en: new Date().toISOString() },
];

export const mockProductos: Producto[] = [
  {
    id: 'prod-1',
    sku: 'ELEC-SENS-01',
    codigo_barras: '7501000100018',
    nombre: 'Sensor Óptico Industrial 24V',
    descripcion: 'Sensor reflectivo de detección de proximidad con alcance de 50cm',
    categoria_id: 'cat-1',
    categoria: mockCategorias[0],
    stock_actual: 45,
    stock_minimo: 10,
    ubicacion_almacen: 'Pasillo A - Estantería 1 - Nivel B',
    unidad_medida: 'UNIDAD',
    precio_unitario: 38.50,
    activo: true,
    creado_en: new Date().toISOString(),
    actualizado_en: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    sku: 'ELEC-MCU-32',
    codigo_barras: '7501000100025',
    nombre: 'Módulo Controlador IoT ESP32',
    descripcion: 'Placa con conectividad WiFi/Bluetooth para telemetría de almacén',
    categoria_id: 'cat-1',
    categoria: mockCategorias[0],
    stock_actual: 8,
    stock_minimo: 15, // Stock bajo
    ubicacion_almacen: 'Pasillo A - Estantería 2 - Nivel A',
    unidad_medida: 'UNIDAD',
    precio_unitario: 12.00,
    activo: true,
    creado_en: new Date().toISOString(),
    actualizado_en: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    sku: 'HERR-CAL-DIG',
    codigo_barras: '7501000100032',
    nombre: 'Calibrador Vernier Digital 150mm',
    descripcion: 'Herramienta de medición milimétrica en acero inoxidable con display LCD',
    categoria_id: 'cat-2',
    categoria: mockCategorias[1],
    stock_actual: 3,
    stock_minimo: 5, // Stock bajo
    ubicacion_almacen: 'Pasillo B - Gabinete 1 - Cajón 3',
    unidad_medida: 'UNIDAD',
    precio_unitario: 64.00,
    activo: true,
    creado_en: new Date().toISOString(),
    actualizado_en: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    sku: 'EMB-CAJA-M',
    codigo_barras: '7501000100049',
    nombre: 'Caja Cartón Doble Canal 40x30x30 cm',
    descripcion: 'Caja resistente para envíos medianos de hasta 20kg',
    categoria_id: 'cat-3',
    categoria: mockCategorias[2],
    stock_actual: 320,
    stock_minimo: 50,
    ubicacion_almacen: 'Área Palets - Posición P-04',
    unidad_medida: 'UNIDAD',
    precio_unitario: 1.45,
    activo: true,
    creado_en: new Date().toISOString(),
    actualizado_en: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    sku: 'EPP-GUANTE-NIT',
    codigo_barras: '7501000100056',
    nombre: 'Pack x10 Guantes de Nitrilo Talla L',
    descripcion: 'Guantes resistentes a grasas y aceites industriales',
    categoria_id: 'cat-4',
    categoria: mockCategorias[3],
    stock_actual: 0, // Sin stock
    stock_minimo: 10,
    ubicacion_almacen: 'Pasillo C - Estantería 4 - Nivel C',
    unidad_medida: 'PACK',
    precio_unitario: 8.90,
    activo: true,
    creado_en: new Date().toISOString(),
    actualizado_en: new Date().toISOString(),
  },
];

export const mockUsuarios: Perfil[] = [
  {
    id: 'usr-admin-1',
    nombre: 'Carlos Vega (Director)',
    email: 'admin@invenio.logistica',
    rol: 'admin',
    activo: true,
    creado_en: new Date().toISOString(),
    actualizado_en: new Date().toISOString(),
  },
  {
    id: 'usr-supervisor-1',
    nombre: 'Elena Morales (Supervisora)',
    email: 'supervisor@invenio.logistica',
    rol: 'supervisor',
    activo: true,
    creado_en: new Date().toISOString(),
    actualizado_en: new Date().toISOString(),
  },
  {
    id: 'usr-operario-1',
    nombre: 'Mario Santos (Operario)',
    email: 'operario@invenio.logistica',
    rol: 'operario',
    activo: true,
    creado_en: new Date().toISOString(),
    actualizado_en: new Date().toISOString(),
  },
  {
    id: 'usr-auditor-1',
    nombre: 'Roberto Díaz (Auditor Calidad)',
    email: 'auditor@invenio.logistica',
    rol: 'auditor',
    activo: true,
    creado_en: new Date().toISOString(),
    actualizado_en: new Date().toISOString(),
  },
];

export const mockMovimientos: MovimientoStock[] = [
  {
    id: 'mov-1',
    producto_id: 'prod-1',
    producto: mockProductos[0],
    usuario_id: 'usr-operario-1',
    usuario: mockUsuarios[1],
    tipo: 'entrada',
    cantidad: 20,
    stock_anterior: 25,
    stock_nuevo: 45,
    motivo: 'Recepción de pedido de proveedor',
    referencia_documento: 'FAC-2026-089',
    creado_en: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'mov-2',
    producto_id: 'prod-2',
    producto: mockProductos[1],
    usuario_id: 'usr-operario-1',
    usuario: mockUsuarios[1],
    tipo: 'salida',
    cantidad: 5,
    stock_anterior: 13,
    stock_nuevo: 8,
    motivo: 'Despacho a línea de ensamblaje #2',
    referencia_documento: 'ORD-781',
    creado_en: new Date(Date.now() - 1800000).toISOString(),
  },
];
